{
   "CVE_data_meta" : {
      "ASSIGNER" : "cve@mitre.org",
      "ID" : "CVE-2016-0772",
      "STATE" : "PUBLIC"
   },
   "affects" : {
      "vendor" : {
         "vendor_data" : [
            {
               "product" : {
                  "product_data" : [
                     {
                        "product_name" : "n/a",
                        "version" : {
                           "version_data" : [
                              {
                                 "version_value" : "n/a"
                              }
                           ]
                        }
                     }
                  ]
               },
               "vendor_name" : "n/a"
            }
         ]
      }
   },
   "data_format" : "MITRE",
   "data_type" : "CVE",
   "data_version" : "4.0",
   "description" : {
      "description_data" : [
         {
            "lang" : "eng",
            "value" : "The smtplib library in CPython (aka Python) before 2.7.12, 3.x before 3.4.5, and 3.5.x before 3.5.2 does not return an error when StartTLS fails, which might allow man-in-the-middle attackers to bypass the TLS protections by leveraging a network position between the client and the registry to block the StartTLS command, aka a \"StartTLS stripping attack.\""
         }
      ]
   },
   "problemtype" : {
      "problemtype_data" : [
         {
            "description" : [
               {
                  "lang" : "eng",
                  "value" : "n/a"
               }
            ]
         }
      ]
   },
   "references" : {
      "reference_data" : [
         {
            "url" : "http://www.openwall.com/lists/oss-security/2016/06/14/9"
         },
         {
            "url" : "https://bugzilla.redhat.com/show_bug.cgi?id=1303647"
         },
         {
            "url" : "https://docs.python.org/3.4/whatsnew/changelog.html#python-3-4-5"
         },
         {
            "url" : "https://docs.python.org/3.5/whatsnew/changelog.html#python-3-5-2"
         },
         {
            "url" : "https://hg.python.org/cpython/raw-file/v2.7.12/Misc/NEWS"
         },
         {
            "url" : "https://hg.python.org/cpython/rev/b3ce713fb9be"
         },
         {
            "url" : "https://hg.python.org/cpython/rev/d590114c2394"
         },
         {
            "url" : "http://www.splunk.com/view/SP-CAAAPSV"
         },
         {
            "url" : "http://www.splunk.com/view/SP-CAAAPUE"
         },
         {
            "url" : "https://security.gentoo.org/glsa/201701-18"
         },
         {
            "url" : "http://rhn.redhat.com/errata/RHSA-2016-1626.html"
         },
         {
            "url" : "http://rhn.redhat.com/errata/RHSA-2016-1627.html"
         },
         {
            "url" : "http://rhn.redhat.com/errata/RHSA-2016-1628.html"
         },
         {
            "url" : "http://rhn.redhat.com/errata/RHSA-2016-1629.html"
         },
         {
            "url" : "http://rhn.redhat.com/errata/RHSA-2016-1630.html"
         },
         {
            "url" : "http://www.securityfocus.com/bid/91225"
         }
      ]
   }
}
